on:
  workflow_dispatch:
jobs:
  ood:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Out of date
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/mirror.key
          sudo chmod 600 ~/.ssh/mirror.key
          echo "$SSH_KNOWN_HOST" > ~/.ssh/known_hosts
          ./scripts/fetch_autobuild.sh
          ./scripts/setup_sysroot.sh
          ./scripts/check_builds.sh base/om4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOST: ${{secrets.SSH_KNOWN_HOST}}
