on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
jobs:
  ood:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Out of date
        run: |
          sudo apt install libarchive-tools
          TAR=$(command -V tar)
          sudo rm -f $TAR
          sudo ln -s $TAR bsdtar
          tar --version
          ./scripts/ood.sh
          cat ood.list
          ./scripts/fetch_autobuild.sh
          ./scripts/setup_sysroot.sh
          for pkg in $(cat ood.list)
          do
          ./scripts/updatever.sh $pkg
          if ./scripts/check_builds.sh $pkg
          then
          git add $pkg/build.sh
          git commit -m "bump $pkg"
          fi
          done
          git push -u origin main
          ./scripts/ood.sh | tee -a issue.md
          if [ ! -z "$(cat issue.md)" ]
          then
          gh issue create -t "Out of date packages $(date -I)" -Fissue.md
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
