on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
jobs:
  ood:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Out of date
        run: |
          set -x
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'example@example.com'
          sudo apt install libarchive-tools
          sudo rm -f /usr/bin/tar
          sudo ln -s bsdtar /usr/bin/tar
          tar --version
          ./scripts/ood.sh
          cat ood.list
          ./scripts/fetch_autobuild.sh
          ./scripts/setup_sysroot.sh
          for pkg in $(cat ood.list)
          do
          ./scripts/updatever.sh $(dirname $pkg) $(basename $pkg)
          if ./scripts/check_builds.sh $pkg
          then
          git add $pkg/build.sh
          git commit -m "bump $pkg"
          fi
          done
          ./scripts/ood.sh | tee -a issue.md
          if [ ! -z "$(cat issue.md)" ]
          then
          gh issue create -t "Out of date packages $(date -I)" -Fissue.md
          fi
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
